Style/Encoding:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 50
Style/HashSyntax:
  Enabled: false

Metrics/ModuleLength:
  Max: 175

Metrics/AbcSize:
  Max: 41

Metrics/PerceivedComplexity:
  Max: 8
