# Use Travis's cointainer based infrastructure
language: ruby
rvm:
- 3.0.1
sudo: false
cache: bundler
addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

env:
  - CHEF_LICENSE=accept

# Ensure we make Chef Workstation's Ruby the default
before_script:
  - eval "$(chef shell-init bash)"
  - chef exec bundle install
script:
  - chef --version
  - chef exec berks install
  - chef exec bundle exec rake test
