name 'minitest-handler'
maintainer 'David Petzel'
maintainer_email 'davidpetzel@gmail.com'
source_url 'https://github.com/btm/minitest-handler-cookbook'
issues_url 'https://github.com/btm/minitest-handler-cookbook/issues'
license 'Apache-2.0'
description 'Installs and configures minitest-chef-handler'
version '1.5.1'

supports 'ubuntu'
supports 'centos'
chef_version '>= 10.0'
